spec:
  replicas: 1
  template:
    spec:
      containers:
# TODO there does not seem to be a valid HTTP URL we can use
# as a liveness check as management requires auth
# and there is no URL on 8080 that doesn't return a 404
#
#      - livenessProbe:
#          httpGet:
#            path: "/"
#            port: 9090
#          initialDelaySeconds: 180
#        readinessProbe:
#          httpGet:
#            path: "/"
#            port: 9090
#          initialDelaySeconds: 10
